<?php

namespace UserBundle\Repository;

/**
 * ClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassRepository extends \Doctrine\ORM\EntityRepository
{
}
