<?php

namespace EventBundle\Repository;

/**
 * AnswerParticipationFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerParticipationFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
