<?php

namespace EventBundle\Repository;

/**
 * EventPropositionVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventPropositionVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
