<?php

namespace EventBundle\Repository;

/**
 * EventPropositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventPropositionRepository extends \Doctrine\ORM\EntityRepository
{
}
