<?php

namespace EventBundle\Repository;

/**
 * ParticipationFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
