<?php

namespace GalleryBundle\Repository;

/**
 * PictureCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
